# Site settings
title: Datamotus
email: info@datamotus.com
description: > # this means to ignore newlines until "baseurl:"
    At Datamotus we have brought together a strong team of data scientists, 
    software engineers, and business analysts to help your business thrive. 
keywords: > # this means to ignore newlines until "baseurl:"
  machine learning, data science
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://datamotus.com/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
exclude: ['*.Rmd']
paginate: 3
paginate_path: "blog/page:num"
